Update fmenu

diff --git a/fmenu b/fmenu
--- a/fmenu
+++ b/fmenu
@@ -1,38 +1,35 @@
 #!/bin/sh
 #
-# summary: a simple posix script for fuzzy searching and launching programs
+# summary: a simple posix script for launching programs with fzf
 # repository: https://github.com/hollowillow/scripts
 #
 # usage: fmenu [arg]
 # description:
-#       
-#       Search through all programs within $PATH using fzf and launch them using enter.
-#       If an argument is provided, it treats it as the initial query.
 #
-# dependencies: fzf
+#       FZF through all programs in $PATH and launch them.
+#       If an argument is provided, it is the initial query.
+#
+# dependencies: fzf, fd (optional, faster)
 
-# create help message from comment block at the head of file
-if [ "$1" = "-h" ]; then
-        sed "1,2d;s/^# //;s/^#$/ /;/^$/ q" "$0"; exit 0
-fi
+# creates a help message from comment block at the head of file
+printHelp() { sed "1,2d;s/^# //;s/^#$/ /;/^$/ q" "$0"; exit 0; }
+{ [ "$1" = '-h' ] || [ "$1" = '--help' ]; } && printHelp
 
-# print all files within path
-printf '%s\n' "$PATH" | tr ':' '\n' | while IFS= read -r DIR; do
-        # significantly faster, however shows even non executable files and directories
-        ls "$DIR"
-        # significantly slower, more accurate results
-        # find "$DIR" -type f -executable -maxdepth 1 -exec basename {} \;
-done | sort -u | 
+printErr() { printf "%s$(basename "$0"): Error: $1\n" >&2; exit 1; }
+command -v fzf >/dev/null || printErr "dependency not found: fzf"
 
-# open in fzf
-fzf \
-        --prompt='run: ' \
-        --header="$(printf '%s\n' 'enter:run' "$FZF_DEFAULT_HEADER")" \
-        --multi \
-        --query="$*" |
+main() {
+        DIRS=$(printf '%s\n' "$PATH" | tr ':' '\n')
 
-# spawn detached program
-while IFS= read -r CMD; do
-        setsid "$CMD" >/dev/null 2>&1 & disown
-        # nohup sh -c "$CMD >/dev/null 2>&1 &"
-done
+        if command -v fd >/dev/null 2>&1; then 
+                CMDS=$(fd --follow --max-depth=1 --type=x --format='{/}' . $DIRS 2>/dev/null | sort -u)
+        else
+                CMDS=$(find -L $DIRS -maxdepth 1 -executable -type f -printf '%f\n' 2>/dev/null | sort -u)
+        fi
+
+        SELECTED=$(printf '%s\n' "$CMDS" | fzf --prompt='run: ' --query="$*" )
+
+        [ -n "$SELECTED" ] && setsid "$SELECTED" >/dev/null 2>&1
+}
+
+main "$*"
