Update fzgit script

diff --git a/fzgit b/fzgit
--- a/fzgit
+++ b/fzgit
@@ -1,29 +1,32 @@
 #!/bin/sh
 #
-# script: fzgrep
-# description: a simple, extensible, POSIX compliant git commit search shell script
-# dependencies: fzf, bat(can be changed to cat but looses syntax highlighting), ripgrep, 
-#               vim/nvim(make sure you have $EDITOR set), xdotool
-# github: https://github.com/hollowillow/scripts
+# summary: a simple posix script for fuzzy searching git commits
+# repository: https://github.com/hollowillow/scripts
 #
-# DEFAULT KEYMAPS
-# enter: type out selected commit hash
-# ctrl-t: toggle preview window
+# usage: fzgit
 #
+# dependencies: fzf, git, wl-clipboard (wayland), xclip (x11)
+
+if [ "$1" = "-h" ]; then
+        sed "1,2d;s/^# //;s/^#$/ /;/^$/ q" "$0"; exit 0
+fi
 
 if [ "$(git rev-parse 2>/dev/null; printf '%s' $?)" -ne 0 ]; then
-        printf '%s\n' "Error: not a git repo" && 
-        exit 1;
-
-else
+        printf '%s\n' "Error: not a git repo" >&2; exit 2
+fi
 
 PREVIEW="git show --color=always {1}"
-git log --oneline \
-        | fzf \
-                --ansi --color=16 \
-                --preview="$PREVIEW" --preview-label="[commit diff]" --preview-window="top" \
-                --bind 'ctrl-t:toggle-preview' \
-        | cut -d' ' -f1 \
-        | xargs xdotool type
 
-fi;
+if [ "$(printenv XDG_SESSION_TYPE)" = wayland ]; then
+        COPY='wl-copy {1}'
+elif [ "$(printenv XDG_SESSION_TYPE)" = x11 ]; then
+        COPY='xclip -i -selection clipboard {1}'
+else 
+        COPY="printf '%s\n' {1}"
+fi
+
+git log --oneline | fzf \
+        --delimiter=' ' \
+        --preview="$PREVIEW" --preview-label="[commit diff]" \
+        --header="$(printf '%s\n' 'enter:copy' "$FZF_DEFAULT_HEADER")" \
+        --bind="enter:become:$COPY"
