update power script

diff --git a/power b/power
--- a/power
+++ b/power
@@ -5,19 +5,31 @@
 #
 # usage: power
 #
-# depedencies: hyprlock (out of the box), systemctl (out of the box)
+# depedencies: systemctl, exit-hyprland (optional script for log out)
 
-# create help message from comment block at the head of file
-if [ "$1" = "-h" ]; then
-        sed "1,2d;s/^# //;s/^#$/ /;/^$/ q" "$0"; exit 0
-fi
+# creates a help message from comment block at the head of file
+printHelp() { sed "1,2d;s/^# //;s/^#$/ /;/^$/ q" "$0"; exit 0; }
+{ [ "$1" = "-h" ] || [ "$1" = "--help" ]; } && printHelp
 
-CHOSEN="$(printf "Lock\nSuspend\nPower Off\nReboot" | fzf --prompt 'power: ')"
+printErr() { printf "%s$(basename "$0"): Error: $1\n" >&2; exit 1; }
+command -v systemctl >/dev/null || printErr "dependency not found: systemctl"
 
-case $CHOSEN in
-        # alter for usage with other utilities
-        "Lock") if [ "$(printf '%s\n' Yes No | fzf --prompt 'confirm: ')" = "Yes" ]; then nohup hyprlock >/dev/null & fi;;
-        "Suspend") if [ "$(printf '%s\n' Yes No | fzf --prompt 'confirm: ')" = "Yes" ]; then systemctl suspend; fi;;
-        "Power Off") if [ "$(printf '%s\n' Yes No | fzf --prompt 'confirm: ')" = "Yes" ]; then systemctl poweroff; fi;;
-        "Reboot") if [ "$(printf '%s\n' Yes No | fzf --prompt 'confirm: ')" = "Yes" ]; then systemctl reboot; fi;;
-esac
+
+main() {
+        # items will be presented in the order they appear here
+        OPTIONS="Power Off\nReboot\nSuspend\nHibernate\nLog Out\n"
+        SELECTED="$(printf "$OPTIONS" | fzf --prompt 'power: ')"
+        [ -z "$SELECTED" ] && exit 0
+
+        # confirm selected invocation can be removed to skip confirmation per option
+        confirmSelection() { printf 'Yes\nNo' | fzf --prompt='confirm: '; }
+        case "$SELECTED" in
+                "Power Off") [ "$(confirmSelection)" = "Yes" ] && systemctl poweroff;;
+                "Reboot") [ "$(confirmSelection)" = "Yes" ] && systemctl reboot;;
+                "Suspend") [ "$(confirmSelection)" = "Yes" ] && systemctl suspend;;
+                "Hiberate") [ "$(confirmSelection)" = "Yes" ] && systemctl hibernate;;
+                "Log Out") [ "$(confirmSelection)" = "Yes" ] && exit-hyprland;;
+        esac
+}
+
+main
