Update wp script

diff --git a/wp b/wp
--- a/wp
+++ b/wp
@@ -3,83 +3,67 @@
 # summary: a simple posix wrapper script for setting wallpapers
 # repository: https://github.com/hollowillow/scripts
 #
-# usage: wp -r|s [-hq] [-d arg]
-# options: 
-#       
-#       -d      specify directory
-#       -h      display this help message
-#       -q      supress all output
-#       -r      set a random wallpaper from directory
-#       -s      select a wallpaper from directory via fzf
+# usage: wp [arg]
+# arguments: 
 #
-# dependencies: fzf, swaybg (wayland), fehbg (x11), libnotify (optional)
+#       random  selects a random wallpaper
+#       select  fuzzy search to select wallpaper
+#       help    bring up this message
+#
+# dependencies: fzf, swaybg (wayland), fehbg (x11)
 
-# exit 0 - successful execution
-# exit 1 - no selection
-# exit 2 - error
+WALLPAPERS_DIR="${WALLPAPERS_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/wallpapers}"
+mkdir -p "$WALLPAPERS_DIR" # create directory if it doesn't already exist
+cd "$WALLPAPERS_DIR" || { printf '%s\n' "Error: $WALLPAPERS_DIR not found"; exit 2; }
 
-WALLPAPERS_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/wallpapers"
-mkdir -p "$AUTOSTART_DIR" # create directory if it doesn't already exist
-
-### define functions ###
-
-sendFeedback() {
-        if [ -z "$QUIET" ]; then
-                printf '%s\n' "$1"; notify-send "$1"
-        fi
+printHelp() {
+        # creates a help message from comment block at the top of the file
+        sed "1,2d;s/^# //;s/^#$/ /;/^$/ q" "$0"; exit 0
 }
 
 setWallpaper() {
         if [ "$(printenv XDG_SESSION_TYPE)" = wayland ]; then
+                pkill swaybg;
                 swaybg --image "$1" &
         elif [ "$(printenv XDG_SESSION_TYPE)" = x11 ]; then
-                fehbg --no-fehbg --bg-scale "$1" &
+                fehbg --no-fehbg --bg-scale "$1" & exit 0
         fi
 }
 
 randomWallpaper() {
-        WALLPAPER="$(\
-                find "$WALLPAPERS_DIR" -type f -not -path '*/\.git/*' |
-                shuf -n 1
-        )"
+        WALLPAPER="$(find . -type f -not -path '*/\.git/*' | shuf -n 1)"
         if [ -n "$WALLPAPER" ]; then 
-                setWallpaper "$WALLPAPER"; sendFeedback "Set random wallpaper."; exit 0
+                setWallpaper "$WALLPAPER";
+                printf '%s\n' "Set random wallpaper.";
         else
-                sendFeedback "No file selected"; exit 1
+                printf '%s\n' "No file selected."; exit 1
         fi
 }
 
 selectWallpaper() {
-        WALLPAPER="$(\
-                find "$WALLPAPERS_DIR" -type f -not -path '*/\.git/*' -exec basename {} \; |
+        # strips files to basename without file extension for nicer searching
+        SELECTED="$(\
+                find . -type f -not -path '*/\.git/*' -exec basename {} \; |
                 sed "s/\.png$//;s/\.jpg$//;s/\.jpeg$//;" |
-                fzf \
-                --prompt "wallpaper: " \
-                --header="$(printf '%s\n' "$FZF_DEFAULT_HEADER")"
+                fzf --prompt "wallpaper: "
         )"
+        # gets back full path
+        WALLPAPER="$(find . -type f -name "*$SELECTED\.*")"
         if [ -n "$WALLPAPER" ]; then 
-                setWallpaper "$(find "$WALLPAPERS_DIR" -type f -name "*$WALLPAPER\.*")"; sendFeedback "Set selected wallpaper"; exit 0
+                pkill swaybg;
+                setWallpaper "$WALLPAPER";
+                printf '%s\n' "Set selected wallpaper"; exit 0
         else
                 sendFeedback "No file selected!"; exit 1
         fi
 }
 
-### parse options ###
-
-while getopts ":d:hqrs" OPT >/dev/null >&2
-do
-        case "$OPT" in
-                d) if [ -d "$OPTARG" ]; then WALLPAPERS_DIR="$OPTARG"; else sendFeedback "Error: \"$OPTARG\" is not a directory" >&2; exit 2; fi;;
-                h) sed "1,2d;s/^# //;s/^#$/ /;/^$/ q" "$0"; exit 0;;
-                q) QUIET=true;;
-                r) randomWallpaper;;
-                s) selectWallpaper;;
-                :) sendFeedback "Error: Option -""${OPTARG}"" requires an argument"; exit 2;;
-                \?) sendFeedback "Error: Option -""${OPTARG}"" is not an option"; exit 2;;
+main() {
+        case $1 in
+                help|-h|--help) printHelp;;
+                random) randomWallpaper;;
+                select) selectWallpaper;;
         esac
-done
-### execute ###
+}
 
-if [ ! -d "$WALLPAPERS_DIR" ]; then
-        sendFeedback "Error: no directory provided"; exit 2
-fi
+main "$@"
